### ISSUE TITLE
snake can cross itself in the 4rd square

### ISSUE THREAD

**Issue by pesachov** [UrielOfir/snake#1]
![image](https://user-images.githubusercontent.com/98988444/152438170-fae2d893-274d-4c93-b849-22b7a09e6b27.png)

**Comment by UrielOfir** [comment]
I fixed this bug in the commit: https://github.com/UrielOfir/snake/commit/e8a549dc67212e8dd31b340ffd9e8b443c19affc
Thank you for letting me know about it :)
